source 'https://rubygems.org'

ruby '3.2.2'

gem 'sinatra', '~> 3.0'
gem 'sinatra-contrib', '~> 3.0'
gem 'puma', '~> 6.0'
gem 'redis', '~> 5.0'
gem 'connection_pool', '~> 2.4'
gem 'jwt', '~> 2.7'
gem 'bcrypt', '~> 3.1'
gem 'rack-attack', '~> 6.7'
gem 'rake', '~> 13.0'
gem 'dotenv', '~> 2.8'
gem 'activesupport', '~> 7.0'

group :development, :test do
  gem 'rspec', '~> 3.12'
  gem 'rack-test', '~> 2.1'
  gem 'mock_redis', '~> 0.36'
  gem 'pry', '~> 0.14'
end
