# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.2.2'

# Web server
gem 'rack'
gem 'rackup'
gem 'puma'

# Redis
gem 'redis'
gem 'connection_pool'

# JSON
gem 'oj'

# Concurrency
gem 'concurrent-ruby'

# Per-request storage
gem 'request_store'

# Logging
gem 'semantic_logger'

group :development, :test do
  gem 'pry'
end
